export const categories = [
  "Breaking News",
  "Pakistan",
  "World",
  "Politics",
  "Business",
  "Economy",
  "Technology",
  "Artificial Intelligence",
  "Startups",
  "Cyber Security",
  "Programming",
  "Mobile",
  "Gadgets",
  "Science",
  "Space",
  "Environment",
  "Climate",
  "Health",
  "Fitness",
  "Mental Health",
  "Medical",
  "Education",
  "Universities",
  "Schools",
  "Scholarships",
  "Jobs",
  "Government Jobs",
  "Private Jobs",
  "Freelancing",
  "Remote Jobs",
  "Sports",
  "Cricket",
  "Football",
  "Tennis",
  "Olympics",
  "Entertainment",
  "Movies",
  "TV Shows",
  "Drama",
  "Music",
  "Celebrities",
  "Lifestyle",
  "Fashion",
  "Food",
  "Travel",
  "Automobile",
  "Real Estate",
  "Finance",
  "Stock Market",
  "Cryptocurrency",
  "Islam",
  "Religion",
  "Opinion",
  "Editorial",
  "Interviews",
  "Culture",
  "History",
  "Photography",
  "Weather",
  "International",
  "Local News",
  "Social Issues",
  "Crime",
  "Law",
  "Agriculture",
  "Tourism",
  "Events",
  "Media",
  "Podcasts",
  "Videos",
  "Infographics"
] as const;

export const primaryNavigationCategories = [
  "Breaking News",
  "Pakistan",
  "World",
  "Politics",
  "Business",
  "Technology",
  "Sports",
  "Entertainment",
  "Health",
  "Education",
  "Jobs",
  "Videos"
] as const;

export const homepageCategories = [
  "Breaking News",
  "Pakistan",
  "World",
  "Politics",
  "Business",
  "Economy",
  "Technology",
  "Artificial Intelligence",
  "Startups",
  "Cyber Security",
  "Science",
  "Health",
  "Education",
  "Jobs",
  "Sports",
  "Entertainment",
  "Lifestyle",
  "Finance",
  "Opinion",
  "Videos"
] as const;

export function categorySlug(category: string) {
  return category.toLowerCase().replaceAll(" ", "-");
}
